### ISSUE TITLE
集成到微信开放工具后

### ISSUE THREAD

**Issue by lilin87788** [sannyzeng/vant-weapp-snippets#2]
1、wxss 不高亮显示了
2、wxml 文件编辑也报错 比如注释就变成了双斜线

**Comment by sannyzeng** [comment]
@lilin87788 v0.0.14 版本已更新，感谢反馈

**Comment by lilin87788** [comment]
我再打开一下

**Comment by lilin87788** [comment]
> 我再打开一下

1、这个安装方式微信开发工具默认的好像是通过id 和 url 安装
2、另外微信开发工具也有自己的插件市场，我搜索vant weapp搜索不到

**Comment by sannyzeng** [comment]
> 

可以在release裡面下載vsix插件離線安裝，在已安裝插件列表那裡右上角有和從vsix安裝，希望幫到你
