### ISSUE TITLE
0.0.14 安装后 {{}} 模板字符串不高亮显示了

### ISSUE THREAD

**Issue by lilin87788** [sannyzeng/vant-weapp-snippets#3]
<img width="1056" alt="image" src="https://github.com/sannyzeng/vant-weapp-snippets/assets/1483811/402c9242-e4b5-450a-af10-ceba9e8b506f">

**Comment by sannyzeng** [comment]
0.0.15版本已修复 @lilin87788

**Comment by lilin87788** [comment]
非常感谢大佬，可惜我不懂，要不然我就pull request 了

**Comment by sannyzeng** [comment]
> 非常感谢大佬，可惜我不懂，要不然我就pull request 了

我也不是很懂，当时为了自己开发方便参考别人的改的，感谢使用😁

**Comment by lilin87788** [comment]
<img width="819" alt="image" src="https://github.com/sannyzeng/vant-weapp-snippets/assets/1483811/f37df3cd-bc18-491c-898d-5c24290c61fe">
好像还是有问题
